# -*- coding: utf-8 -*-
"""fix_datetime_utc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VllQVj499FyZsYNDpuhZ2naCz91diH2d
"""

import re

# List of files and the line numbers to check/fix
files_to_fix = {
    'Historic_news_data.py': 17,
    'get_news.py': 17,
    'last_30days_news.py': 33,
}

def fix_file(filename):
    print(f"Fixing {filename} ...")
    with open(filename, 'r') as f:
        lines = f.readlines()

    # Regex pattern to match datetime.datetime.utcnow()
    pattern = re.compile(r'datetime\.datetime\.utcnow\(\)')

    # Replace all occurrences in the file lines
    fixed_lines = []
    for line in lines:
        fixed_line = pattern.sub('datetime.now(timezone.utc)', line)
        fixed_lines.append(fixed_line)

    # Check and add import for timezone if missing
    imports = [line for line in fixed_lines if line.strip().startswith('from datetime import')]
    if not any('timezone' in imp for imp in imports):
        # Insert timezone import after first datetime import or at the top if none found
        inserted = False
        for i, line in enumerate(fixed_lines):
            if line.startswith('from datetime import datetime'):
                # Append timezone to the import line
                fixed_lines[i] = line.strip().rstrip() + ', timezone\n'
                inserted = True
                break
        if not inserted:
            # No datetime import line found, add at the top
            fixed_lines.insert(0, 'from datetime import datetime, timezone\n')

    # Write back the fixed content
    with open(filename, 'w') as f:
        f.writelines(fixed_lines)

    print(f"{filename} fixed.\n")

def main():
    for file in files_to_fix:
        fix_file(file)

if __name__ == '__main__':
    main()