# -*- coding: utf-8 -*-
"""news_fetcher

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wJ0tSH-HwqZ4Cb-aQW2lgo9heeO61-k
"""

import requests
import time
import pandas as pd
from datetime import datetime

def fetch_news(api_key, query, from_date, to_date, max_results=3000, page_size=100):
    articles = []
    num_pages = max_results // page_size

    for page in range(1, num_pages + 1):
        url = (
            f'https://newsapi.org/v2/everything?'
            f'q={query}&'
            f'from={from_date.strftime("%Y-%m-%d")}&'
            f'to={to_date.strftime("%Y-%m-%d")}&'
            f'sortBy=publishedAt&'
            f'pageSize={page_size}&'
            f'page={page}&'
            f'apiKey={api_key}'
        )

        response = requests.get(url)
        if response.status_code != 200:
            print(f"❌ Error on page {page}: {response.status_code}")
            print(response.text)
            break

        data = response.json()
        if 'articles' not in data or not data['articles']:
            print("⚠️ No more articles found.")
            break

        for item in data['articles']:
            articles.append({
                'url': item.get('url'),
                'source': item['source'].get('name') if item.get('source') else None,
                'title': item.get('title'),
                'author': item.get('author'),
                'published_at': item.get('publishedAt'),
                'summary': item.get('description'),
                'content': item.get('content')
            })

        time.sleep(1)  # to avoid hitting API rate limits

    return pd.DataFrame(articles)