version: '3.8'

services:
  bbc-producer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - existing-kafka-network

networks:
  existing-kafka-network:
    external: true
    name: news-pipeline_default
